name: workouts_reminder_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.2.2
  serverpod_auth_idp_server: 3.2.2
  http: ^1.2.2

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.2.2
  test: ^1.25.5
